spring:
  application:
    name: KeyValueDbService

  jpa:
    show-sql: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:pozer
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

DatabaseGarbageCollector:
  fixedRateDelayMillis: 200

DumpFile:
  fileName: dump.json

